Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y apache2
    systemctl enable apache2
  SHELL
  config.vm.network :forwarded_port, guest: 80, host: 8080
end
Vagrant.configure("2") do |secondvm|
  secondvm.vm.box = "centos/7"
end