Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

 
  config.vm.network :forwarded_port, guest: 8090, host: 8080
  config.vm.network :forwarded_port, guest: 3306, host: 3306
 
  config.vm.provider "virtualbox" do |virtualbox|
  
    virtualbox.memory = "4000"
  end
 
  config.vm.provision "shell", path: "provisionscript.sh"
end
